# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_stock_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='unit',
            field=models.CharField(max_length=250),
        ),
    ]
