# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_auto_20171027_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='unit',
            field=models.FloatField(default=0),
        ),
    ]
