# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_auto_20171027_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='date',
            field=models.DateTimeField(default='timezone.now'),
        ),
    ]
