# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 09:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_remove_stock_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
