# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0014_auto_20171201_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='unit',
            field=models.CharField(max_length=650),
        ),
    ]
