# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0015_auto_20171204_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
