# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('quantity', models.IntegerField(default=0)),
                ('unit_price', models.FloatField(default=0)),
                ('amount', models.FloatField(default=0)),
            ],
            options={
                'verbose_name_plural': 'expenses',
            },
        ),
    ]
