# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 19:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expenses_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenses',
            name='total',
        ),
    ]
