# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 19:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_expenses_sum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenses',
            old_name='sum',
            new_name='total_amount',
        ),
    ]
