# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale', models.FloatField(default=0)),
                ('expense', models.FloatField(default=0)),
                ('balance', models.FloatField(default=0)),
            ],
            options={
                'verbose_name_plural': 'balance',
            },
        ),
    ]
